### ISSUE TITLE
Generate .Net client for the exchange Rest API

### ISSUE THREAD

**Issue by monsieurleberre** [trakx/trakx-tools#164]
It should be possible to autogenerate it from https://app.swaggerhub.com/apis/TrakxIo/trakx-exchange-api/2.2  using Nswag.
This should be placed in its own project like Trakx.Exchange.ApiClient and possible to re-generate on rebuild!

This will allow:
- querying labels for logged in users, and getting adequate permissions
- getting wallet addresses and balances for users, allowing to transfer issued and redeemed indices directly from the exchange onto their wallets
- probably a lot more ... 😄

**Comment by AymericNoel** [comment]
Try to resolve in #166
