### ISSUE TITLE
Resolve dependency injection issue for Exchange Client API

### ISSUE THREAD

**Issue by monsieurleberre** [trakx/trakx-tools#232]
We need to be able 
- to have a switch in the ExchangeApiConfiguration to decide which type of ICredentialProvider is use (api key vs barong cookie)
- to not have the explicit calls to constructor in the AddSingleton(... ) of the various api clients

**Comment by AymericNoel** [comment]
Done in #257.

Furthermore, when injecting ExchangeClient, we can choose apiKey or barongCookie in parameter.
