### ISSUE TITLE
AutoGenerate .env stub file and add it on Readme.md

### ISSUE THREAD

**Issue by monsieurleberre** [trakx/trakx-tools#342]
The .env file needed to run our projects is getting more and more complex.
It is going to be hard to maintain manually and it would be a lot easier to have the section of the Readme autogenerated by simply running a unit test.
We can first make sure the test fails if all the .env variables are not here, but it is better to make sure that the test passes easily and tries to modify the Readme before running.

As for finding out which variables are required, one idea is to reflect on all Trakx.**.*Configuration classes and makes sure they are defined.
To make it easier we can create a "Secret" attribute in Dotnet utils, and that (and maybe a Required) in all projects requiring a password. Then reflection is a bit less random to deal with.

Any other idea is welcome!

**Comment by monsieurleberre** [comment]
I am assigning that to both of you guys but feel free to un-assign if you don't want it...

**Comment by carlos-takeapps** [comment]
@monsieurleberre , you mean to update the Readme.md locally on build or test run and then push the modified file, right? I am aware that there are also some options to update the Readme file by an action, but since that action is usually triggered by a PR, the process of updating the readme is a subsequent commit to the same PR. It may become a little cumbersome.

**Comment by monsieurleberre** [comment]
yes I think it is much better as a test: since you are supposed to run them before committing, the file automatically gets updated, the test fails if the file is corrupt or something like that. It feels like a much shorter iteration cycle.

**Comment by AymericNoel** [comment]
@carlos-takeapps Do you take this one ?

**Comment by carlos-takeapps** [comment]
Ok, sure
