### ISSUE TITLE
Design UI for erc20 wrapping / unwrapping

### ISSUE THREAD

**Issue by monsieurleberre** [trakx/trakx-tools#63]
- Allowed users need to be able to choose between supported currencies, give the source address from which the funds are coming and the target address where the wrapped funds are expected.

- This should work symmetrically for wrapping and unwrapping.

- Any user should be able to see that the total wrapped token issued for all currencies is the same as the balance on trakx public address for the native token.

**Comment by AymericNoel** [comment]
Here is the UI : https://docs.google.com/presentation/d/1_bNI9b5b_LxCNz6dJWiWmCQ-8sfNUrQg0KV6eZym3H0/edit#slide=id.p

**Comment by monsieurleberre** [comment]
👍 I have added comments on the drawing, good start!

**Comment by monsieurleberre** [comment]
Cool, let's have a look at what's next 🚀 👍
